name: Quick Tests

# Run quick tests on every push and PR
on:
  push:
  pull_request:

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-test.txt
    
    - name: Run quick tests
      run: |
        pytest tests/ -v --tb=short -x
    
    - name: Check import structure
      run: |
        python -c "import service_config_foundry; print('✅ Package imports successfully')"
        python -c "from service_config_foundry import Service, ServiceLocation; print('✅ Main classes import successfully')"
